### ISSUE TITLE
GPLv2 and MIT license compatibility

### ISSUE THREAD

**Issue by bbvch13531** [poirin/MyDiary#7]
## Type of issue
- Doc

## Description
- MyDiary uses MySQL that follows [GPLv2](https://www.mysql.com/about/legal/licensing/oem/) 
MyDiary should not follows MIT license because MIT is not compatible to GPLv3.0.
 Please check your license compatibility please.

**Comment by poirin** [comment]
Should i change to GPL license?
I am also using source based on MIT.

**Comment by bbvch13531** [comment]
MyDiary seems to uses [MySQL](https://www.mysql.com/about/legal/licensing/oem/) that follows GPLv2

**Comment by poirin** [comment]
If I'm using MIT open source and GPL open source at the same time, should I follow the GPL license?
Sorry to keep asking.

**Comment by bbvch13531** [comment]
I'm glad to keep talking to you @poirin :smiley: 
Yes, MIT is permissive license but GPL is copyleft license.
These links will useful to you!
[네이버 오픈소스가이드](https://naver.github.io/OpenSourceGuide/book/UsingOss/the-legal-side-of-opensource.html#licensedef)
[카피레프트](https://ko.m.wikipedia.org/wiki/카피레프트)
[퍼미시브 라이선스](https://ko.m.wikipedia.org/wiki/퍼미시브_라이선스)
[라이선스 비교표](https://olis.or.kr/license/compareGuide.do)
If you have more question about license, just leave comment freely

**Comment by poirin** [comment]
Thank you very much for your kind answers to my questions.😃😃
